// action API/TRIVIA
const REQUEST_STARTED = 'REQUEST_STARTED';
const REQUEST_SUCESS_API = 'REQUEST_SUCESS_API';
const REQUEST_ERROR_API = 'REQUEST_ERROR_API';
const NEXT_QUESTION = 'NEXT_QUESTION';

export { REQUEST_STARTED, REQUEST_SUCESS_API, REQUEST_ERROR_API, NEXT_QUESTION };
