// action API/TRIVIA
const REQUEST_STARTED = 'REQUEST_STARTED';
const REQUEST_SUCESS_API = 'REQUEST_SUCESS_API';
const REQUEST_ERROR_API = 'REQUEST_ERROR_API';
const NEXT_QUESTION = 'NEXT_QUESTION';
const ADD_DATA_USER = 'ADD_DATA_USER';

export {
  REQUEST_STARTED,
  REQUEST_SUCESS_API,
  REQUEST_ERROR_API,
  NEXT_QUESTION,
  ADD_DATA_USER,
};
